config/routes.rb
Rails.application.routes.draw do



  root 'demo#index'

  resources :subjects

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections

  resources :sections do
    member do
      get :delete
    end
  end

  get 'demo/index'

  get 'demo/hello'

  get 'demo/other_hello'

  get 'demo/git'

  get 'demo/escape_output'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  #self.table_name = "admin_users"
  has_and_belongs_to_many :pages
  has_many :section_edits
  has_many :sections, :through => :section_edits
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

  belongs_to :subject
  has_many :sections
  has_and_belongs_to_many :admin_users
end

app/models/section.rb
class Section < ApplicationRecord

  belongs_to :page
  has_many :section_edits
  has_many :admin_users, :through => :section_edits
end

app/models/section_edit.rb
class SectionEdit < ApplicationRecord
  belongs_to :admin_user
  belongs_to :section
end

app/models/subject.rb
class Subject < ApplicationRecord

  has_many :pages

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("position ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :search, lambda {|query| where (["name LIKE?", "%#{query}%"]) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

  layout 'application'

  def index
    render('index')
  end

  def hello
    @array = [1,2,3,4,5]
    @id = params['id']
    @page = params[:page]
    render('hello')

  end

  def other_hello
    redirect_to(:action => 'index')

  end

  def git
    redirect_to('https://github.com/Natellus')

  end

  def escape_output
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  layout 'admin'
  def index
    @pages = Page.order(:position)
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
    @page_count = Page.count + 1
    @subjects = Subject.sorted
  end

  def create
    @page = Page.new(page_params)
    if @page.save
      flash[:notice] = "Page created succesfully"
      redirect_to(pages_path)
    else
      @page_count = Page.count +1
      @subjects = Subject.sorted
      render ('new')
    end
  end

  def edit
    @page = Page.find(params[:id])
    @page_count = Page.count
    @subjects = Subject.sorted
  end

  def update
    @page = Page.find(params[:id])

    if @page.update_attributes(page_params)
      flash[:notice] = "Page updated successfully"
      redirect_to(pages_path)
    else
      @page_count = Page.count
      @subjects = Subject.sorted
      render('edit')
    end

  end


  def delete
    @page = Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] = "Page deleted successfully"
    redirect_to(pages_path)
  end

  private

  def page_params
    params.require(:page).permit(:name, :position, :subject_id, :visible)

  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  layout 'admin'
  def index
    @sections = Section.order(:position)
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
    @section_count = Section.count + 1
    @pages = Page.order(:position)
  end

  def create
    @section = Section.new(sections_params)
    if @section.save
      flash[:notice] = "Section created successfully"
      redirect_to(sections_path)
    else
      @section_count = Section.count +1
      @pages = Page.order(:position)
      render('new')
    end

  end


  def edit
    @section = Section.find(params[:id])
    @section_count = Section.count
    @pages = Page.order(:position)
  end

  def update
    @section = Section.find(params[:id])
    if @section.update_attributes(sections_params)
      flash[:notice] = "Section updated successfully"
      redirect_to(sections_path)
    else
      @section_count = Section.count
      @pages = Page.order(:position)
      render('edit')
    end
  end

  def delete
    @section = Section.find(params[:id])
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    flash[:notice] = "Section deleted successfully"
    redirect_to(sections_path)
  end

  private

  def sections_params
    params.require(:section).permit(:page_id, :name, :position, :visible, :content)
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  layout 'admin'

  def index
    @subjects = Subject.sorted

  end

  def show
    @subject = Subject.find(params[:id])

  end

  def new
    @subject = Subject.new({:name => 'Default'})
    @subject_count = Subject.count + 1
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      flash[:notice] = "Subject created successfully"
      redirect_to(subjects_path)
    else
      @subject_count = Subject.count + 1
      render('new')

    end


  end

  def edit
    @subject = Subject.find(params[:id])
    @subject_count = Subject.count

  end

  def update
    @subject = Subject.find(params[:id])

    if @subject.update_attributes(subject_params)
      flash[:notice] = "Subject updated successfully"
      redirect_to(subjects_path(@subject))
    else
      @subject_count = Subject.count
      render('edit')

    end

  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "Subject '#{@subject.name}' destroyed successfully"
    redirect_to(subjects_path)

  end

  private

  def subject_params
    params.require(:subject).permit(:name, :position, :visible, :created_at)
  end
end

app/controllers/test2_controller.rb
class Test2Controller < ApplicationController
  def index
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def status_tag(boolean, options={})
    options[:true_text] ||= ''
    options[:false_text] ||= ''

    if boolean
      content_tag(:span, options[:true_text], :class => 'status true')
    else
      content_tag(:span, options[:false_text], :class => 'status false')
    end
  end

end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/test2_helper.rb
module Test2Helper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/demo/escape_output.html.erb
<% evil_string = "<script>alert(Gotcha!); </script>" %>
<% good_string = "<strong> Welcome to mu site!</strong>" %>
<% evil_string %> <br/>
<% good_string %> <br/>

app/views/demo/hello.html.erb
<h1>Hello world from hello!</h1>
<% 1 + 2 %>
<%= 1 + 2 %>
<% variable = "world" %>
<%= "hello #{variable}" %>
<br>
<% 3.times do |n| %>
  <%= n %> <br>
<% end %>
<% @array.each do |a| %>
  <%= a %>
<% end %> <br>
<%= link_to('index page', {:action => 'index'}) %> <br>
id: <%= @id %> <br>
id: <%= params[:id] %><b> <br>
  Page: <%= @page %> <br>
  Next page: <%= @page.to_i + 1 %>

app/views/demo/index.html.erb
<h1>Hello world from index!</h1>
<a href="demo/hello">Hello page 1</a><br>
<%=  link_to('Hello page 2', {:action => 'hello'}) %>    <br>
<%=  link_to('Hello with paramentrs', {:action => 'hello', :page => 5, :id => 20}) %>    <br>
<%= link_to('Roar', '#', :onclick => "jsRoar('JavaScript'); return true;") %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Cms: <%= @page_title || "Admin Area" %></title>
    <%= stylesheet_link_tag('admin', :media => 'all') %>
  </head>
  <body>
    <div id="header">
      <h1>Simple CMS Admin</h1>
    </div>
    <div id ="main">
      <% if !flash[:notice].blank? %>
        <div clas="notice">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <div id ="content">
        <%= yield %>
      </div>
    </div>
    <div id="footer">
      <p id="copyright">&copy; banana.com</p>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag('application', media: 'all')  %>
    <%= javascript_include_tag('application') %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<table class="Pages form fields" >
  <tr >
    <th>Name</th>
    <td> <%= f.text_field(:name) %></td>
  </tr>
  <tr >
    <th>Position</th>
    <td><%= f.select(:position, 1..@page_count) %></td>
  </tr>
  <tr >
    <th>Subject ID</th>
    <td><%= f.select(:subject_id, @subjects.map{|s| [s.name, s.id]}) %></td>
  </tr>
  <tr >
    <th>Visible?</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
</table>

app/views/pages/delete.html.erb
<%= link_to("<< Back to list", pages_path, :class => 'back-link') %>
<div class="Page delete">
  <h2>Delete Page</h2>
  <%= form_for(@page, :method => 'delete') do |f| %>
    <p> Are you sure you want to permanently delete this Page?</p>
    <p class ="reference-name"><%= f.object.name %></p>
    <div class ="form-buttons">
      <%= f.submit("Delete Page") %>
    </div>
  <% end %>
</div>

app/views/pages/edit.html.erb
<%= link_to("<< Back to list", pages_path, :class => 'back-link') %>
<div class="Pages edit">
  <h2>Update Page</h2>
  <%= form_for(@page) do |f| %>
    <%= render(:partial =>'form', :locals =>{:f => f})%>
    <div class ="form-buttons">
      <%= f.submit("Update Page") %>
    </div>
  <% end %>
</div>

app/views/pages/index.html.erb
<div class="Pages index">
  <h2>Pages</h2>
  <%= link_to("Add new Page", new_page_path, :class => 'action new') %>
  <table class="listing" summary="Page list">
    <tr class="header">
      <th>#</th>
      <th>Page</th>
      <th>Subject ID</th>
      <th>Visible </th>
      <th>Sections</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.position %></td>
        <td><%= page.name %></td>
        <td><%= page.subject_id %></td>
        <td class="center"> <%= status_tag(page.visible) %> </td>
        <td class="center"> <%= page.sections.size %> </td>
        <td class="actions">
          <%= link_to("Show", page_path(page), :class => 'action now') %>
          <%= link_to("Edit", edit_page_path(page), :class => 'action now') %>
          <%= link_to("Delete", delete_page_path(page), :class => 'action now') %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/pages/new.html.erb
<%= link_to("<< Back to list", pages_path, :class => 'back-link') %>
<div class="pages new">
  <h2>Create Pages</h2>
  <%= form_for(@page) do |f| %>
    <%= render(:partial =>'form', :locals =>{:f => f})%>
    <div class ="form-buttons">
      <%= f.submit("Create Page") %>
    </div>
  </div>
<% end %>

app/views/pages/show.html.erb
<%= link_to("<< Back to list", pages_path, :class => 'back-link') %>
<div class="Pages show">
  <h2>Show Page</h2>
  <table class="Page detail view" >
    <tr >
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr >
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    <tr >
      <tr >
        <th>Subject ID</th>
        <td><%= @page.subject_id %></td>
      </tr>
      <tr >
        <th>Visible?</th>
        <td><%= @page.visible ? 'true' : 'false' %></td>
      </tr>
      <tr >
        <th>Created</th>
        <td><%= @page.created_at %></td>
      </tr>
      <tr >
        <th>Updated</th>
        <td><%= @page.updated_at %></td>
      </tr>
    </table>
  </div>

app/views/sections/_form.html.erb
<table class="Section form fields" >
  <tr >
    <th>Name</th>
    <td> <%= f.text_field(:name) %></td>
  </tr>
  <tr >
    <th>Position</th>
    <td><%= f.select(:position, 1..@section_count) %></td
  </tr>
    <tr >
      <th>Page</th>
      <td><%= f.select(:page_id, @pages.map {|p| [p.name, p.id]}) %></td>
    </tr>
    <tr >
      <th>Visible?</th>
      <td><%= f.check_box(:visible) %></td>
    </tr>
    <tr >
      <th>Content type</th>
      <td>
        <%= f.radio_button(:content, 'text') %> Text
     <%= f.radio_button(:content, 'HTML') %> HTML 
    </td>
    </tr>
    <tr >
      <th>Content</th>
      <td><%= f.text_area(:content, :size => '40x10') %></td>
    </tr>
  </table>

app/views/sections/delete.html.erb
<%= link_to("<< Back to list", sections_path, :class => 'back-link') %>
<div class="Page delete">
  <h2>Delete Page</h2>
  <%= form_for(@section, :method => 'delete') do |f| %>
    <p> Are you sure you want to permanently delete this Section?</p>
    <p class ="reference-name"><%= f.object.name %></p>
    <div class ="form-buttons">
      <%= f.submit("Delete Section") %>
    </div>
  <% end %>
</div>

app/views/sections/edit.html.erb
<%= link_to("<< Back to list", sections_path, :class => 'back-link') %>
<div class="Sections edit">
  <h2>Update Section</h2>
  <%= form_for(@section) do |f| %>
    <%= render(:partial => 'form', :locals =>{:f => f}) %>
    <div class ="form-buttons">
      <%= f.submit("Update Section") %>
    </div>
  <% end %>
</div>

app/views/sections/index.html.erb
<div class="Sections index">
  <h2>Sections</h2>
  <%= link_to("Add new Section", new_section_path, :class => 'action new') %>
  <table class="listing" summary="Page list">
    <tr class="header">
      <th>#</th>
      <th>Name</th>
      <th>Page ID</th>
      <th>Visible </th>
      <th>Actions</th>
    </tr>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.position %></td>
        <td><%= section.name %></td>
        <td><%= section.page_id %></td>
        <td class="center"> <%= status_tag(section.visible) %> </td>
        <td class="actions">
          <%= link_to("Show", section_path(section), :class => 'action now') %>
          <%= link_to("Edit", edit_section_path(section), :class => 'action now') %>
          <%= link_to("Delete", delete_section_path(section), :class => 'action now') %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/sections/new.html.erb
<%= link_to("<< Back to list", sections_path, :class => 'back-link') %>
<div class="sections new">
  <h2>Create Sections</h2>
  <%= form_for(@section) do |f| %>
    <div class ="form-buttons">
      <%= f.submit("Create Section") %>
      <%= render(:partial => 'form', :locals =>{:f => f}) %>
    </div>
  </div>
<% end %>

app/views/sections/show.html.erb
<%= link_to("<< Back to list", sections_path, :class => 'back-link') %>
<div class="Pages show">
  <h2>Show Page</h2>
  <table class="Section detail view" >
    <tr >
      <th>Name</th>
      <td><%= @section.name %></td>
    </tr>
    <tr >
      <th>Position</th>
      <td><%= @section.position %></td>
    </tr>
    <tr >
      <tr >
        <th>Page ID</th>
        <td><%= @section.page_id %></td>
      </tr>
      <tr >
        <th>Visible?</th>
        <td><%= @section.visible ? 'true' : 'false' %></td>
      </tr>
      <tr >
        <tr >
          <th>Content</th>
          <td><%= @section.content %></td>
        </tr>
        <tr >
          <th>Created</th>
          <td><%= @section.created_at %></td>
        </tr>
        <tr >
          <th>Updated</th>
          <td><%= @section.updated_at %></td>
        </tr>
      </table>
    </div>

app/views/subjects/_form.html.erb
<table class="Subject form fields" >
  <tr >
    <th>Name</th>
    <td> <%= f.text_field(:name) %></td>
  </tr>
  <tr >
    <th>Position</th>
    <td><%= f.select(:position, 1..@subject_count) %></td>
  </tr>
  <tr >
    <th>Visible?</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
  <tr >
    <th>Created</th>
    <td><%= f.datetime_select(:created_at, :order => [:month, :day, :year ]) %></td>
  </tr>
</table>

app/views/subjects/delete.html.erb
<%= link_to("<< Back to list", subjects_path, :class => 'back-link') %>
<div class="subject delete">
  <h2>Delete Subject</h2>
  <%= form_for(@subject, :method => 'delete') do |f| %>
    <p> Are you sure you want to permanently delete this subject?</p>
    <p class ="reference-name"><%= f.object.name %></p>
    <div class ="form-buttons">
      <%= f.submit("Delete Subject") %>
    </div>
  <% end %>
</div>

app/views/subjects/edit.html.erb
<%= link_to("<< Back to list", subjects_path, :class => 'back-link') %>
<div class="subjects edit">
  <h2>Update Subject</h2>
  <%= form_for(@subject) do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    <div class ="form-buttons">
      <%= f.submit("Update Subject") %>
    </div>
  <% end %>
</div>

app/views/subjects/index.html.erb
<% @page_title = "All Subjects" %>
<div class="subjects index">
  <h2>Subjects</h2>
  <%= image_tag('plus_sign.png', :size => '11x11', :alt => '+') %>
  <%= link_to("Add new Subject", new_subject_path, :class => 'action new') %>
  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.position %></td>
        <td><%= subject.name %></td>
        <td class="center"><%= status_tag(subject.visible) %> </td>
        <td class="center"><%= subject.pages.size %> </td>
        <td class="actions">
          <%= link_to("Show", subject_path(subject.id), :class => 'action now') %>
          <%= link_to("Edit", edit_subject_path(subject), :class => 'action now') %>
          <%= link_to("Delete", delete_subject_path(subject), :class => 'action now') %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<%= link_to("<< Back to list", subjects_path, :class => 'back-link') %>
<div class="subjects new">
  <h2>CreateSubject</h2>
  <%= form_for(@subject) do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    <div class ="form-buttons">
      <%= f.submit("Create Subject") %>
    </div>
  </div>
<% end %>

app/views/subjects/show.html.erb
<%= link_to("<< Back to list", subjects_path, :class => 'back-link') %>
<div class="subjects show">
  <h2>Show Subject</h2>
  <table class="Subject detail view" >
    <tr >
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr >
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr >
      <th>Visible?</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr >
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr >
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>
</div>

app/views/test2/index.html.erb
<h1>Hello World (test)</h1>